# Generated by Django 5.1.5 on 2025-03-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
