# Generated by Django 5.1.5 on 2025-02-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default='Sedan', max_length=100),
        ),
    ]
