# Generated by Django 5.1.5 on 2025-03-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tourpackage_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplan',
            name='accommodation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='inclusion',
            field=models.TextField(null=True),
        ),
    ]
