# Generated by Django 5.1.5 on 2025-03-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_tourplan_day_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
