# Generated by Django 5.1.5 on 2025-03-20 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tourpackage_created_at_tourpackage_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='highlight_icons/')),
            ],
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/'),
        ),
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(upload_to='tours_images/'),
        ),
        migrations.AddField(
            model_name='country',
            name='highlight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='tours.highlight'),
        ),
    ]
