# Generated by Django 5.1.5 on 2025-03-20 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_highlight_remove_tourpackage_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='tour_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tourpackage'),
        ),
    ]
