# Generated by Django 5.1.5 on 2025-03-20 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tourimage_tour_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'service_provider']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
