# Generated by Django 5.1.5 on 2025-03-20 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tourpackage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='highlight',
        ),
        migrations.AddField(
            model_name='highlight',
            name='country',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tours.country'),
        ),
    ]
