# Generated by Django 5.1.5 on 2025-03-20 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_remove_country_highlight_highlight_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhenToGo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('start_month', models.CharField(max_length=20)),
                ('end_month', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='when_to_go', to='tours.country')),
            ],
        ),
    ]
