# Generated by Django 5.1.5 on 2025-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_category_activity_custompackage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default='kigali', null=True),
        ),
    ]
