# Generated by Django 5.1.5 on 2025-03-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_activity_location_alter_activity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='price',
            field=models.CharField(default=2000, max_length=1000),
        ),
    ]
