# Generated by Django 5.1.5 on 2025-03-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
